   - type: web
    name: discord-bot-taobao
    env: python
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    healthCheckPath: /
